INSERT INTO USER (ID, USER_ID, PASSWORD, NAME, EMAIL) VALUES (1, 'jeon', '1234', '정환', 'jeon@naver.com');
INSERT INTO USER (ID, USER_ID, PASSWORD, NAME, EMAIL) VALUES (2, 'jeon2', '1234', '정환2', 'jeon2@naver.com');

INSERT INTO QUESTION (ID, WRITER_ID, TITLE, CONTENTS, CREATE_DATE) VALUES (1, 1, '제목 입니다. (JEON)', '내용 입니다. 1', CURRENT_TIMESTAMP());
INSERT INTO QUESTION (ID, WRITER_ID, TITLE, CONTENTS, CREATE_DATE) VALUES (2, 2, '제목 입니다. (JEON2)', '내용 입니다. 2', CURRENT_TIMESTAMP());

